// src/components/ui/card.tsx
import type { HTMLAttributes } from 'react'

import { cn } from '@/lib/utils'

export function Card({ className, ...props }: HTMLAttributes<HTMLDivElement>) {
  return <div className={cn('rounded-2xl border border-border bg-card text-card-foreground shadow-card', className)} {...props} />
}

export function CardHeader({ className, ...props }: HTMLAttributes<HTMLDivElement>) {
  return <div className={cn('border-b border-border p-5', className)} {...props} />
}

export function CardTitle({ className, ...props }: HTMLAttributes<HTMLHeadingElement>) {
  return <h2 className={cn('text-lg font-semibold tracking-tight', className)} {...props} />
}

export function CardContent({ className, ...props }: HTMLAttributes<HTMLDivElement>) {
  return <div className={cn('p-5', className)} {...props} />
}

// src/components/ui/Card.svelte
<script lang="ts">
  import type { Snippet } from 'svelte'
  import type { HTMLAttributes } from 'svelte/elements'

  import { cn } from '@/lib/utils'

  interface CardProps extends HTMLAttributes<HTMLDivElement> {
    header?: Snippet
    children?: Snippet
    contentClass?: string
  }

  let { class: className = '', contentClass = 'p-5', header, children, ...rest }: CardProps = $props()
</script>

<div {...rest} class={cn('rounded-lg border border-border bg-card text-card-foreground shadow-card', className)}>
  {#if header}
    <div class="border-b border-border p-5">
      {@render header()}
    </div>
  {/if}
  <div class={contentClass}>
    {@render children?.()}
  </div>
</div>
