// src/components/ui/input.tsx
import type { InputHTMLAttributes, SelectHTMLAttributes } from 'react'

import { cn } from '@/lib/utils'

export function Input({ className, ...props }: InputHTMLAttributes<HTMLInputElement>) {
  return (
    <input
      className={cn(
        'h-11 w-full rounded-xl border border-border bg-card px-3 text-sm text-foreground outline-none transition placeholder:text-muted-foreground focus:border-primary focus:ring-2 focus:ring-primary/20',
        className,
      )}
      {...props}
    />
  )
}

export function Select({ className, ...props }: SelectHTMLAttributes<HTMLSelectElement>) {
  return (
    <select
      className={cn(
        'h-11 w-full rounded-xl border border-border bg-card px-3 text-sm font-medium text-foreground outline-none transition focus:border-primary focus:ring-2 focus:ring-primary/20',
        className,
      )}
      {...props}
    />
  )
}

// src/components/ui/Input.svelte
<script lang="ts">
  import type { HTMLInputAttributes } from 'svelte/elements'

  import { cn } from '@/lib/utils'

  interface InputProps extends HTMLInputAttributes {
    value?: string | number | null
  }

  let {
    class: className = '',
    type = 'text',
    value = $bindable(''),
    ...rest
  }: InputProps = $props()
</script>

<input
  {...rest}
  {type}
  bind:value
  class={cn(
    'h-11 w-full rounded-xl border border-border bg-card px-3 text-sm text-foreground outline-none transition placeholder:text-muted-foreground focus:border-primary focus:ring-2 focus:ring-primary/20',
    className,
  )}
/>
